language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
before_install:
  - sudo apt-get install git mercurial -y
install:
  - "touch README"
  - "pip install . --use-mirrors"
  - "pip install -r test-requirements.txt --use-mirrors"
script: nosetests tests
